version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
    assignees:
      - "antonengelhardt"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    assignees:
      - "antonengelhardt"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependencies"
    assignees:
      - "antonengelhardt"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
