image: "zivgitlab.wwu.io/m_wiga01/rust-docker-tools/rust-docker-tools:latest"

stages:
  - test
  - build
  - documentation
  - deploy-docs

cache:
  paths:
    - target/

test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo-deny check licenses
    - cargo-deny check advisories
    - cargo clippy
    - cargo test --workspace --verbose

build:
  only:
    - main
  stage: build
  script:
    - cargo build --target wasm32-wasip1 --release
  artifacts:
    paths:
      - target/wasm32-wasip1/release/wasm_oidc_plugin.wasm
    expire_in: 1 week

pages:
  cache: {}
  stage: deploy-docs
  script:
    - cargo doc --document-private-items --no-deps
    - echo "<meta http-equiv=refresh content=0;url=wasm_oidc_plugin/index.html>" > target/doc/index.html
    - mv target/doc public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
