image: "zivgitlab.wwu.io/m_wiga01/rust-docker-tools/rust-docker-tools:latest"

stages:
  - test
  - build
  - documentation

cache:
  paths:
    - target/

test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo-deny check licenses
    - cargo-deny check advisories
    - cargo clippy
    - cargo test --workspace --verbose

build:
  only:
    - main
  stage: build
  script:
    - cargo build --target wasm32-wasi --release
  artifacts:
    paths:
      - target/wasm32-wasi/release/wasm_oidc_plugin.wasm
    expire_in: 1 week

documentation:
  only:
    - main
  stage: documentation
  script:
    - cargo doc --document-private-items
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week
