[package]
publish = false
name = "wasm-oidc-plugin"
version = "0.0.1"
authors = ["WWU Cloud Developer <cloud@uni-muenster.de"]
description = "WASM OIDC Envoy Plugin"
license = "Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
proxy-wasm = "0.2.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "debuginfo"
