apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: example-namespace
type: Opaque
data:
  password: base64-encoded-github-pat #! this is the base64 encoded github personal access token
