apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wasm-oidc-plugin-certificate
  namespace: wasm-oidc-plugin
spec:
  secretName: wasm-oidc-plugin-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: demo.wasm-oidc-plugin.ae02.de
  dnsNames:
    - demo.wasm-oidc-plugin.ae02.de
