# Alternative 2: Use pre-built [Docker-Image](https://hub.docker.com/r/antonengelhardt/wasm-oidc-plugin) from Docker Hub

apiVersion: apps/v1
kind: Deployment

metadata:
  name: wasm-oidc-plugin
  namespace: wasm-oidc-plugin
  labels:
    app: wasm-oidc-plugin

spec:
  selector:
    matchLabels:
      app: wasm-oidc-plugin
  replicas: 1

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: wasm-oidc-plugin

    spec:
      containers:
        - name: envoy
          image: ghcr.io/antonengelhardt/wasm-oidc-plugin:latest

          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 300m
              memory: 300Mi

          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml

          livenessProbe:
            httpGet:
              path: /
              port: 10000
            initialDelaySeconds: 15
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 10000
            initialDelaySeconds: 15
            periodSeconds: 5

          ports:
            - containerPort: 10000
              name: http
              protocol: TCP

          command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--concurrency", "5"]

      volumes:
        - name: envoy-config
          configMap:
            name: wasm-oidc-plugin-config
            defaultMode: 420
            items:
              - key: envoy.yaml
                path: envoy.yaml

      restartPolicy: Always
