apiVersion: v1
kind: Service
metadata:
  name: wasm-oidc-plugin-service
  namespace: wasm-oidc-plugin
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 10000
  selector:
    app: wasm-oidc-plugin
