name: Test and Build Wasm OIDC Plugin

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: zivgitlab.wwu.io/m_wiga01/rust-docker-tools/rust-docker-tools:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          rustc --version && cargo --version
          cargo clippy
          cargo test --workspace --verbose

  build:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: zivgitlab.wwu.io/m_wiga01/rust-docker-tools/rust-docker-tools:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          cargo build --target wasm32-wasi --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wasm_oidc_plugin.wasm
          path: target/wasm32-wasi/release/wasm_oidc_plugin.wasm
