name: Documentation

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --document-private-items

      - name: Fix file permissions
        shell: sh
        run: |
          chmod -c -R +rX "target/doc" |
          while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Generate index.html file
        run: |
          echo "<meta http-equiv=refresh content=0;url=wasm_oidc_plugin/index.html>" > target/doc/index.html

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

      - name: Zip documentation
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          cd target/doc
          zip -r docs .
          cd ../..

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: target/doc/docs.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}

    steps:
      - name: Deploy documentation
        id: pages
        uses: actions/deploy-pages@v2
