name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: antonengelhardt/rust-docker-tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: Rust version
        run: rustc --version && cargo --version

      - name: Clippy
        run: cargo clippy --release --all-targets --target=wasm32-wasi

      - name: Fmt
        run: cargo fmt -- --check

      - name: Test
        run: cargo test --workspace --verbose

      - name: Build
        run: cargo build --release --target wasm32-wasi
